In [78]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [79]:
filename = "property_loss1541.csv"
df = pd.read_csv(filename)

In [80]:
df.head()

,STATE,latitude,longitude,Number of Inhabited villages,Number of Uninhabited villages,Number of towns,Number of households,Total Population,Males Population,Females Population,Area (In sq. km),Population per sq. km.,WIND SPEED,YEAR,STORM NAME,property loss,CASUALITIES
0,0,0.108925,0.931385,0.529412,0.354839,0.6875,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,55,2013,0.075758,0.173077,0.369565
1,0,0.108925,0.931385,0.529412,0.354839,0.6875,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,120,2022,0.151515,0.211538,0.565217
2,0,0.108925,0.931385,0.529412,0.354839,0.6875,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,130,2018,0.257576,0.826923,0.782609
3,0,0.108925,0.931385,0.529412,0.354839,0.6875,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,100,2010,0.333333,0.000000,0.173913
4,0,0.108925,0.931385,0.529412,0.354839,0.6875,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,75,2017,0.454545,0.461538,0.652174

In [81]:
# df.sample(frac=0.3, random_state=1)

In [82]:
# df = df.sample(frac=0.3, replace=True, random_state=1)

In [83]:
unique_states = df['STATE'].unique()

In [84]:
# Create an empty list to store sampled rows
sampled_rows = []

In [85]:
# Loop through unique state values and sample one row for each state
for state in unique_states:
    # Sample one row for the current state
    row = df[df['STATE'] == state].sample(1)
      # Append the sampled row to the list
    sampled_rows.append(row)
# Concatenate the sampled rows into a new DataFrame
sampled_df = pd.concat(sampled_rows)

In [86]:
# Reset the index of the sampled DataFrame
sampled_df.reset_index(drop=True)

,STATE,latitude,longitude,Number of Inhabited villages,Number of Uninhabited villages,Number of towns,Number of households,Total Population,Males Population,Females Population,Area (In sq. km),Population per sq. km.,WIND SPEED,YEAR,STORM NAME,property loss,CASUALITIES
0,0,0.108925,0.931385,0.529412,0.354839,0.68750,0.970588,0.647059,0.382353,0.205882,0.024017,0.71875,155,2016,0.939394,0.538462,0.717391
1,1,0.230321,0.274940,0.352941,0.161290,0.59375,0.294118,0.970588,0.676471,0.588235,0.803646,0.50000,100,2023,0.530303,0.980769,0.391304
2,2,0.716548,0.972193,0.705882,0.709677,0.46875,0.411765,0.235294,0.941176,0.852941,0.244625,0.25000,240,1970,0.090909,0.942308,0.000000
3,3,0.702752,1.000000,0.323529,0.064516,0.25000,0.852941,0.529412,0.117647,0.117647,0.229123,0.65625,140,2021,0.969697,0.423077,0.478261
4,4,0.664776,0.687824,0.500000,0.838710,0.21875,0.176471,0.088235,0.735294,0.676471,0.275075,0.03125,220,2021,0.893939,0.192308,0.434783
5,5,0.519302,0.441298,0.676471,0.000000,0.84375,0.352941,0.117647,0.794118,0.647059,0.000245,1.00000,165,1998,0.015152,0.519231,0.152174
6,6,0.447496,0.017597,0.264706,0.870968,0.18750,0.764706,0.411765,0.000000,0.029412,0.394969,0.28125,240,2019,0.409091,0.269231,0.760870
7,7,0.778344,0.212844,0.882353,0.000000,0.84375,0.882353,0.617647,0.205882,0.088235,0.001347,0.87500,155,2017,0.712121,0.961538,0.586957
8,8,0.259517,0.054733,0.235294,0.000000,0.90625,0.794118,0.352941,0.088235,1.000000,0.000237,0.34375,65,2005,0.818182,0.038462,0.543478
9,9,0.563774,0.001999,0.058824,0.967742,0.06250,0.617647,0.058824,1.000000,0.911765,0.004246,0.06250,100,2004,0.727273,0.980769,0.956522
10,10,0.769683,0.203112,0.441176,0.290323,0.87500,0.558824,0.264706,0.970588,0.882353,0.010730,0.62500,165,2008,0.621212,0.365385,0.282609
11,11,0.874016,0.209906,0.176471,0.774194,0.56250,0.000000,0.735294,0.470588,0.382353,0.573375,0.50000,85,2022,0.878788,0.634615,0.630435
12,12,1.000000,0.084792,0.852941,0.387097,0.15625,0.647059,0.382353,0.029412,0.000000,0.129108,0.84375,280,2023,0.560606,0.153846,0.326087
13,13,0.586624,0.638705,0.205882,0.483871,0.81250,0.235294,0.882353,0.647059,0.558824,0.162599,0.12500,110,2017,0.575758,0.500000,0.239130
14,14,0.144491,0.198479,0.794118,0.580645,0.12500,0.470588,0.029412,0.911765,0.794118,0.649328,0.15625,260,2020,0.136364,0.326923,0.173913
15,15,0.000000,0.182259,0.411765,0.516129,0.37500,0.823529,0.558824,0.176471,0.147059,0.232858,0.68750,130,2020,0.696970,0.788462,0.304348
16,16,0.065442,0.000000,0.382353,0.193548,0.53125,0.088235,0.794118,0.441176,0.411765,0.560362,0.53125,260,1991,1.000000,0.230769,0.260870
17,17,0.488198,0.161871,0.000000,0.032258,0.75000,0.911765,0.588235,0.147059,0.176471,0.113445,0.96875,85,2008,0.833333,0.980769,0.891304